#!/usr/bin/env sh

set -e

echo "Starting..."

if [ ! pip3 ]
then
    echo "+ Installing pip3..."
    sudo apt-get install -y python3-pip
fi

if [ ! virtualenv ]
then
    echo "+ Installing virtualenv..."
    sudo pip3 install virtualenv
fi

if [ ! -d venv ]
then
    echo "+ Creating virtualenv..."
    python3 -m venv venv
    . venv/bin/activate
    pip install -r requirements.txt
    deactivate
fi

. venv/bin/activate
flask run --host 0.0.0.0 --port 9999 --reload $@
